### ISSUE TITLE
国服7.0版本的opcode好像没推上去

### ISSUE THREAD

**Issue by ReparoZ** [zhyupe/ffxiv-opcode-worker#7]
看FFXIVOpcodes库里只有7.00的分支，内容是空的。7.0的没有。是不是因为这个原因所以Teamcraft还有matcha插件都无法使用？（假期打扰非常抱歉）

**Comment by zhyupe** [comment]
您好，由于脚本对主版本更新的版本号处理存在一些问题，之前推送的数据有误，目前已经修复并重新推送。具体可以关注 https://github.com/karashiiro/FFXIVOpcodes/pull/199

由于主版本更新可能涉及到部分包结构变化，即使在 opcode 更新后，部分功能也可能需要单独适配。由于近期时间安排问题，暂时无法完成对 matcha 的适配。
